### ISSUE TITLE
[NumberGuesser] Каменский?

### ISSUE THREAD

**Issue by pavel-b-novikov** [Kvinster/nsudotnet#1]
```if (null == s)```

Вот объясните мне четко и по полочкам почему вы так пишете? В чем смысл?

**Comment by Kvinster** [comment]
На первом курсе, еще на C, приучили, так и осталось. Смысл весь был в том, чтобы избежать случайного присваивания, если вдруг вместо "==" случайно напишешь "=" - если слева константа, то будет ошибка компиляции.

**Comment by pavel-b-novikov** [comment]
Почему это правило не применимо к C#?

**Comment by pavel-b-novikov** [comment]
У меня создалось ощущение, что вы соблюдаете это правило даже не думая.

Кусок из Enigma:

```while (null != (currentString = sr.ReadLine()))```

**Comment by Kvinster** [comment]
Полагаю, потому что в C# есть bool, и присваивание в условии if'a приведет к провальной попытке неявной конвертации присвоенного значения (в данном случае строки) к bool'ю. Опять же, ошибка компиляции
Да, уже настолько привык так писать, что в большинстве случаев не задумываясь ставлю константу слева. Это сильно плохо? Я полагаю, кроме как на читаемости (это тоже важно, конечно), это ни на чем не сказывается?

**Comment by pavel-b-novikov** [comment]
Очень сказывается на вашей репутации, выдавая неопытного недофаната C. В остальном проблем особых нет.
