### ISSUE TITLE
[NumberGuesser] Вывод минут

### ISSUE THREAD

**Issue by pavel-b-novikov** [Kvinster/nsudotnet#2]
```.ToString(CultureInfo.CurrentCulture)```

Объясните смысл этой строки.

**Comment by Kvinster** [comment]
А чего именно смысл нужно объяснить? Если указания культуры, то это скорее минутная блажь - среда попросила указать явно, я позволил ей это сделать. Если использования там ToString в принципе, то тут уже вопрос хороший, пожалуй, можно было и без этого обойтись; не помню даже, что заставило меня использовать ToString. Думаю, ничего важного.

**Comment by pavel-b-novikov** [comment]
То есть вы сделали то, что вам предлагает система, даже не понимая что делаете и строите свой код на предположениях и догадках?
Нет, так не пойдет.

**Comment by Kvinster** [comment]
Я сделал то, что предложила система, да, но вместе с тем я, как, по крайней мере, мне кажется, понимал, что делаю - явное указание культуры в ToString явно не было для меня таинством, которое я без задней мысли сотворил, лишь бы угодить системе. Я, вероятно, не уделил ему достаточно мыслительной деятельности, раз не обнаружил сразу отсутствующую необходимость вызывать ToString вообще, но и сказать, что не понимал, что происходит, когда жал Alt+Enter не могу.

**Comment by pavel-b-novikov** [comment]
И все-таки я желаю услышать объяснение что делает эта конструкция.

**Comment by Kvinster** [comment]
Выдает строковое представление числа (в данном случае), составленное с учетом языка и прочих региональных параметров, заданных в указанном CultureInfo

**Comment by pavel-b-novikov** [comment]
Какие у числа могут быть региональные параметры?

**Comment by Kvinster** [comment]
Не уверен насчет всех, но полагаю, разделитель между целой и десятичной частями, опционально - разделитель между разрядами
