### ISSUE TITLE
[LinesCounter] Регексы

### ISSUE THREAD

**Issue by pavel-b-novikov** [Kvinster/nsudotnet#3]
Нет нет нет, я ценю вашу способность пользоваться регексами, но в данной задаче они излишни. Уберите. При том желательно так, чтобы по всем строкам проход осуществлялся только один раз

**Comment by pavel-b-novikov** [comment]
Ну?

**Comment by Kvinster** [comment]
А, регексы я убрал, до переделки самого алгоритма так и не дошел. Если этого недостаточно для зачета задачи, то до выставления оценки и не доделаю уже, вероятно, ибо я среди тех, кто уже пришел к деканату
